services:
  bot:
    image: "ghcr.io/zolotarevalexandr/inpulse_bot:${DOCKER_TAG_BOT:-latest}"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - "./settings.yaml:/app/settings.yaml:ro"
    environment:
      TZ: Europe/Moscow
    deploy:
      resources:
        limits:
          memory: 1g

  db:
    image: "postgres:17.1"
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d inpulse" ]
      timeout: 5s
      start_period: 30s
      interval: 1m
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inpulse

  redis:
    image: "redis:7.2.4-alpine"
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"

volumes:
  postgres:
  redis:
