"""Add calendars table

Revision ID: 28e62a71a49f
Revises: 298387f727b6
Create Date: 2026-07-08 17:59:47.983122

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '28e62a71a49f'
down_revision: str | Sequence[str] | None = '298387f727b6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('calendar_events', sa.Column('calendar_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('calendar_events_user_id_fkey'), 'calendar_events', type_='foreignkey')
    op.create_foreign_key(None, 'calendar_events', 'calendars', ['calendar_id'], ['id'], ondelete='CASCADE')
    op.drop_column('calendar_events', 'user_id')
    op.drop_column('users', 'ical_url')
    op.drop_column('users', 'ical_last_synced')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ical_last_synced', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('ical_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('calendar_events', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'calendar_events', type_='foreignkey')
    op.create_foreign_key(op.f('calendar_events_user_id_fkey'), 'calendar_events', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('calendar_events', 'calendar_id')
    op.drop_table('calendars')
    # ### end Alembic commands ###
