"""Add whitelisted_users table

Revision ID: 298387f727b6
Revises: ca48621aa7ce
Create Date: 2026-07-08 17:29:58.768483

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '298387f727b6'
down_revision: str | Sequence[str] | None = 'ca48621aa7ce'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whitelisted_users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whitelisted_users')
    # ### end Alembic commands ###
