"""Add whitelisted_users table

Revision ID: 298387f727b6
Revises: ca48621aa7ce
Create Date: 2026-07-08 17:29:58.768483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '298387f727b6'
down_revision: Union[str, Sequence[str], None] = 'ca48621aa7ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whitelisted_users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whitelisted_users')
    # ### end Alembic commands ###
