"""subscriptions

Revision ID: bc19b7585c99
Revises: 28e62a71a49f
Create Date: 2026-07-08 20:25:34.168526

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bc19b7585c99'
down_revision: str | Sequence[str] | None = '28e62a71a49f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whitelisted_users')
    op.add_column('users', sa.Column('role', sa.String(length=16), server_default='free', nullable=False))
    op.add_column('users', sa.Column('premium_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'premium_until')
    op.drop_column('users', 'role')
    op.create_table('whitelisted_users',
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('added_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('telegram_id', name=op.f('whitelisted_users_pkey'))
    )
    # ### end Alembic commands ###
